### ISSUE TITLE
Check the assignment - minimum viable store database

### ISSUE THREAD

**Issue by AlekseiILitvinov** [AlekseiILitvinov/HomeworkStoreDatabase#1]
Не знаю, правильно ли я понял задание - я сделал набор запросов, которыми создается таблица, в которой можно держать незарегистрированных пользователей, можно составлять историю продаж, фильтровать по статусам заказов. Логика соответствующего сервиса, естественно, не написана.

**Comment by coursar** [comment]
Норм, меня больше интересовали таблицы и связи. Когда сервис будете делать, увидите, что где не так ))
