### ISSUE TITLE
Нет ли ограничения уникальности на это поле?

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/HomeworkStoreDatabase#3]
https://github.com/AlekseiILitvinov/HomeworkStoreDatabase/blob/3c017a4fae23aad3931fd7acc86c7066c9d07634/requests.sql#L16

**Comment by AlekseiILitvinov** [comment]
Предположительно, может возникнуть ситуация, когда пользователь А зарегистрировался с номером телефона, потом этот номер телефона каким-то образом достался пользователю Б и он пытается зарегистрироваться. Я пока сделал 
```UNIQUE (name, phone)```
но мне интересно, как это реально делается. Ведь у многих интернет-магазинов есть вход только по номеру телефона.

**Comment by coursar** [comment]
Телефон - аналог логина, должен быть уникальным (после подтверждения). Детали обсудим на лекции - напомните.
