### ISSUE TITLE
order_id, в таком виде вы не можете ссылаться на много заказов, только на один

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/HomeworkStoreDatabase#4]
https://github.com/AlekseiILitvinov/HomeworkStoreDatabase/blob/3c017a4fae23aad3931fd7acc86c7066c9d07634/requests.sql#L30

**Comment by AlekseiILitvinov** [comment]
Моя логика была в том, что у одного заказа может быть несколько инвойсов (например, если оплата по одному не проходит и пользователь указывает другие платежные данные), а каждый инвойс указывает на один заказ. В заказе может быть несколько товаров, которые попадают в sales.
Я добавил NOT NULL, но мне кажется, что "счёт на оплату" должен указывать только на один заказ. Если это на практике делается иначе, то я, конечно, поменяю - вставлю в orders указание на invoiceId.
